In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [8]:
df = pd.read_csv('kc_house_data.csv')


df.drop(["id","date","zipcode","lat","long","sqft_living15","sqft_lot15"], axis = 1, inplace= True)
df

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0      221900.0         3       1.00         1180      5650     1.0   
1      538000.0         3       2.25         2570      7242     2.0   
2      180000.0         2       1.00          770     10000     1.0   
3      604000.0         4       3.00         1960      5000     1.0   
4      510000.0         3       2.00         1680      8080     1.0   
...         ...       ...        ...          ...       ...     ...   
21608  360000.0         3       2.50         1530      1131     3.0   
21609  400000.0         4       2.50         2310      5813     2.0   
21610  402101.0         2       0.75         1020      1350     2.0   
21611  400000.0         3       2.50         1600      2388     2.0   
21612  325000.0         2       0.75         1020      1076     2.0   

       waterfront  view  condition  grade  sqft_above  sqft_basement  \
0               0     0          3      7        1180              0   
1               0     0          3      7        2170            400   
2               0     0          3      6         770              0   
3               0     0          5      7        1050            910   
4               0     0          3      8        1680              0   
...           ...   ...        ...    ...         ...            ...   
21608           0     0          3      8        1530              0   
21609           0     0          3      8        2310              0   
21610           0     0          3      7        1020              0   
21611           0     0          3      8        1600              0   
21612           0     0          3      7        1020              0   

       yr_built  yr_renovated  
0          1955             0  
1          1951          1991  
2          1933             0  
3          1965             0  
4          1987             0  
...         ...           ...  
21608      2009             0  
21609      2014             0  
21610      2009             0  
21611      2004             0  
21612      2008             0  

[21613 rows x 14 columns]

In [9]:
reg= linear_model.LinearRegression()
reg.fit(df[['bedrooms','bathrooms','sqft_living','sqft_lot','floors','waterfront','view','condition','sqft_above','sqft_basement','yr_built','yr_renovated']],df[['price','grade']])


LinearRegression()

In [12]:
reg.coef_

array([[-5.60090976e+04,  6.24013414e+04,  1.77055578e+02,
        -3.50561615e-01,  4.47825960e+04,  5.37142650e+05,
         6.18991512e+04,  1.91579262e+04,  1.07972567e+02,
         6.90830111e+01, -2.85448140e+03,  1.07243737e+01],
       [-1.38389557e-01,  1.34259192e-01,  5.07591527e-04,
        -7.63299323e-07,  1.64136831e-01, -2.96500906e-01,
         1.34230203e-01,  2.79830741e-03,  4.16636744e-04,
         9.09547828e-05,  5.75664480e-03,  1.72168867e-05]])

In [26]:
reg.intercept_

array([ 5.49522638e+06, -5.60825076e+00])

In [28]:
reg.predict([[5,3,1960,5000,1,0,0,5,1050,910,1965,0]])


c:\Users\K Madan Mohan Reddy\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[4.55414055e+05, 7.10381477e+00]])